name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install required dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Test
      run: npm test
